// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
 
const awsmobile = {
   "aws_project_region": "us-east-1",
   "aws_cognito_identity_pool_id": "us-east-1:3b830264-7230-405a-bdbe-160b51a30cd7",
   "aws_cognito_region": "us-east-1",
   "aws_user_pools_id": "us-east-1_oUkIqzyMU",
   "aws_user_pools_web_client_id": "692e901lee1knr8068t8o1na4v",
   "oauth": {},
   "aws_appsync_graphqlEndpoint": "https://4uce6mm6i5akhgc6u4tgtgvxcq.appsync-api.us-east-1.amazonaws.com/graphql",
   "aws_appsync_region": "us-east-1",
   "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
   "aws_user_files_s3_bucket": "adioc492d9a3e7204c369b78b9a304571a10215215-adio",
   "aws_user_files_s3_bucket_region": "us-east-1"
};
 
 
export default awsmobile;